version: '3'
services:
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./backend:/app:cached
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build: docker/php
        volumes:
            - ./backend:/app:cached
        working_dir: /app
